### ISSUE TITLE
This repository is a copy paste from another project and must indicate so

### ISSUE THREAD

**Issue by vvo** [JureSotosek/npm-to-elasticsearch#1]
Hi, owner and initial creator of https://github.com/algolia/npm-search/ here.

I am glad our code served you well and you were able to create an npm to Elasticsearch replication.

We worked hard on this codebase to make it resilient.
I am reaching out to ask you to update your repository and your README to include:
- The original MIT license file from Algolia: https://github.com/algolia/npm-search/blob/master/LICENSE
- A mention in your README that this project was originally developed by Algolia
- Update your README to indicate: License MIT Algolia, Inc

You can definitely add your own MIT license in it but the original one from Algolia must be here.

As a side note, even without speaking about our license, MIT, Algolia. It's always a very fair move to mention the people and code that inspired you into making your own solution. Original developers will be glad you mention their work instead of making it look like it's completely yours (which was maybe not your main motivation initially).

Alternatively, we are very open on making npm-search original repo a more complete solution that can synchronize to both Algolia or ElasticSearch. Since the code is already almost ready to do that, we would gladly accept any contribution going this direction.

Thanks, let me know what you think.

**Comment by JureSotosek** [comment]
Hi,

I am sorry, it was my plan to include you and give you credit in the README but i just haven't come around to doing so.

Will update README immediately.

Thanks for doing the work you do.

**Comment by JureSotosek** [comment]
I would like to add though that somewhat big chunks of code and logic are changed and done differently.

But still, yes, it is very much modeled after the [npm-search](https://github.com/algolia/npm-search) by Algolia

**Comment by JureSotosek** [comment]
Are the changes sufficient? @vvo

**Comment by vvo** [comment]
All good thanks!
